# Generated by Django 2.0.3 on 2018-05-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('userName', models.TextField(primary_key=True, serialize=False)),
                ('serialNumber', models.TextField()),
                ('unitUUID', models.TextField()),
                ('authorized', models.BooleanField()),
                ('addTime', models.DateTimeField(auto_now=True)),
                ('timeOut', models.DateTimeField()),
                ('newUpdate', models.BooleanField()),
                ('continueUser', models.BooleanField()),
                ('updateInfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('message', models.TextField()),
                ('timeInfo', models.DateTimeField()),
            ],
        ),
    ]
