# Generated by Django 2.0.3 on 2018-05-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPInfo',
            fields=[
                ('appName', models.TextField(primary_key=True, serialize=False)),
                ('newUpdate', models.BooleanField()),
                ('continueUser', models.BooleanField()),
                ('updateInfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='continueUser',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='newUpdate',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='updateInfo',
        ),
    ]
