# Generated by Django 2.0.3 on 2018-05-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180512_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='currentVersion',
            field=models.TextField(null=True),
        ),
    ]
